export const ADD_TO_BASKETLIST = 'ADD_TO_BASKETLIST';
export const REMOVE_FROM_BASKETLIST = 'REMOVE_FROM_BASKETLIST';
export const INCREASE_PRODUCT_AMOUNT = 'INCREASE_PRODUCT_AMOUNT';
export const DECREASE_PRODUCT_AMOUNT = 'DECREASE_PRODUCT_AMOUNT';
